### ISSUE TITLE
Cluster API changes

### ISSUE THREAD

**Issue by adomasven** [cormacrelf/citeproc-rs#21]
I would like to advocate for a change in the Driver API for clusters. The majority of citeproc clients that integrate citing with a document processor have a very specific workflow. There are 2 states that the document is in.

1. The document is being edited by the user via the document processor, where edits are done to text and possibly citations are being copied in from other documents, moved around the existing document and deleted.
2. The user is using the citeproc client (e.g. Zotero) to insert or edit citation clusters, at which point the citeproc client uses citeproc to update the document in bulk, including processing any citations that have appeared or disappeared.

During (2) the citeproc client has a full snapshot of the document with all clusters in order as they appear in the document, including multiple clusters in a single footnote, or citations that appear sequentially in text, then in a footnote (which is in the main body of text) and then in text again. I.e. all citations are naturally representable as an array in the order of appearance in the document.

The citeproc-js API for cluster update works somewhat well with this representation. When updating a particular citation, you slice off all the previous citations before the existing one to a `citationsPre` array and all the following citations to a `citationsPost` array. This is kind of cumbersome in its own right in that for each cluster update that you do in a single document update you need to generate new pre and post arrays, but at least the operation of slicing the known snapshot citation array is rather natural.

The current citeproc-rs Driver API requires manual renumbering of clusters whenever their order changes, which means that the citeproc-rs client has to keep track of which indices it has supplied to the driver and renumber the clusters manually for each document citation update, which is rather cumbersome.

The most natural way to interact with this API would be to be able to insert all clusters into the citeproc-rs Driver without specifying their position first, and then specify the order of their appearance in the document with a separate function call as an array of IDs (with tuplets for note numbers). E.g.

```updateClusterOrder(clusters: [ClusterID | [ClusterID, NoteNumber]])```

This would also be the natural way to tell the Driver about Clusters that have been removed.

I may be overlooking something about how note citations are handled and this is probably not the ideal way for the processor to represent cluster data internally but this has always been my imagination of how an ideal API designed for citeproc clients that integrate with a document processor would look like.

**Comment by cormacrelf** [comment]
You don’t have to keep track of which indices you have supplied and which you haven’t. The processor is exceedingly lazy, and will not recompute anything due to an index that hasn’t actually changed its value. So you can renumber clusters whenever you have a suspicion that something has changed, and don’t worry about it. And each one can just be a dump of the whole ordering.

So we’re on the same page:

1. Add, replace and remove clusters to your heart’s content. As many times as you like.
2. Only need to renumber once, right before you grab batchedUpdates.
3. Slicing is easy but arguably `clientClusters.map(cluster => [cluster.id, cluster.number])` is even easier

Is the suggestion only different in that clusters missing from the array are deleted? If so, I’m not sure Il I see it, unless your word processing interaction doesn’t give you a heads up when text gets removed and a cluster should therefore be deleted, in which case I completely understand — that would be a pretty hard requirement! I could add a variant that does this. I still see removeCluster working well in editors that have a bit more access and control over document content.

**Comment by adomasven** [comment]
> The processor is exceedingly lazy

This is overall great to hear

> Is the suggestion only different in that clusters missing from the array are deleted?

And you do not have to do special handling for note cluster numbering when multiple clusters are in the same note.

> unless your word processing interaction doesn’t give you a heads up when text gets removed [...] I still see removeCluster working well in editors that have a bit more access and control over document content

At least in Zotero's case we do not have that fine level of access with none of our supported editors: Word, Word for Mac, LibreOffice and Google Docs, simply because these editors do not provide any APIs to listen for field removal events. So any citeproc clients integrating with these editors are in the same boat. We are thinking about integration for Word Online and as far as I know there isn't anything like that there either. Even if any of the word processors did have the APIs, we probably wouldn't use them since calls to/from the doc processors are time costly and the biggest bottleneck in overall integration speed.

> You don’t have to keep track of which indices you have supplied and which you haven’t.

What will happen if you supply two clusters with the same `inText` number? Will one overwrite the other? Will an error be thrown? When? This is can happen if you have A, B, C clusters, then remove B and add D, going to the sequence A, C, D. Now D is the new 2, but you would have already set C as 2. The API either has to throw an error upon `insertCluster()` call or silently ignore this until either `renumberClusters()` is called and the idx clash is resolved or `batchedUpdate()` is called and an error is thrown then. Either way it makes the API cumbersome or ambiguous (without careful study of the docs, which means this has to be documented carefully), or both.

**Comment by cormacrelf** [comment]
The only time any processing happens is while batchedUpdates is running. EVERY other call is very simply setting a K/V pair, doing no checks, and returning immediately. It is expected that things will be out of sync, hence these methods returning nothing. The numbers are just values in a dictionary, which help determine sorting order. They can’t overwrite each other. If they don’t change, sorting is unchanged, and no processing needs to happen. What would be cumbersome is trying to supply all the numbering at both points remove(B) and add(D) — nobody cares about whether the numbering is correct between those two operations. So I didn’t require that.

I’m handling another concern here as well — JSON serialisation overhead. It’s very costly to JSON-cycle every cluster in the document on every change, especially if most of them are untouched. So the solution permits the exact minimum of call overhead — upsert the cluster that changed, and maybe renumber, and even then, avoid serialising the entire list of numbers. I don’t think you’re suggesting anything wildly inefficient but it’s good to note.

One other note is that this method does one better than citeproc-js’ laziness — you get lazy bibliography updates too. Sequential calls to processCitationCluster will pick up every changed citation cluster, but might miss or double up on bibliography changes, so the API doesn’t give them to you. (I have never investigated whether pCC will report changed clusters from further down in the document, but if it does, this could also double up on processing.)

> What will happen if you supply two clusters with the same inText number?

So after all that the answer is “nothing”, but I don’t think the sorting will deterministically tiebreak, due to hashmap iteration order, so they might swap positions in a bibliography sometimes. I guess I could flag that as a warning in batchedUpdates, but at least for inText, the “order you supplied them to the renumbering call with deletion” thing seems a better fit that makes this impossible. I’m thinking more like two different calls, for the two different regimes.

```ts
updateInTextClusterOrder(inText: ClusterId[]);
```

Will think more about note numbers.

**Comment by adomasven** [comment]
> The only time any processing happens is while batchedUpdates is running. EVERY other call is very simply setting a K/V pair, doing no checks, and returning immediately. It is expected that things will be out of sync, hence these methods returning nothing. The numbers are just values in a dictionary, which help determine sorting order. They can’t overwrite each other. If they don’t change, sorting is unchanged, and no processing needs to happen. What would be cumbersome is trying to supply all the numbering at both points remove(B) and add(D) — nobody cares about whether the numbering is correct between those two operations. So I didn’t require that.

Right, but my point is that just looking at what API methods are available as a naive client it is unclear what will happen for my example above: whether any Errors will be thrown and if they will be, when; and if not why not, since having multiple clusters with the same inText number is an error that can cause ibid and bibl ordering errors.

> I’m handling another concern here as well — JSON serialisation overhead. It’s very costly to JSON-cycle every cluster in the document on every change, especially if most of them are untouched.

I'm not entirely sure what JSON-cycling means here? Is this just having non-integer arguments in API arguments or something more? How inefficient is it? How does it scale based on the number of items to serialize?

Why what I proposed is less efficient? It's just changing the `renumberClusters()` signature into a slightly different one and removing some attributes from `insertCluster()` calls

> I’m thinking more like two different calls, for the two different regimes.

What two different regimes? Note and intext styles? I don't know if this is relevant on the processor side, but people do insert intext citations in their footnotes (and somewhat more bizarrely, sometimes copy out the citations from footnotes into the body of the text when using a note style). We currently supply these to citeproc-js with a note number, but if that is not meaningful for citation generation with any of the styles, I see what you mean with `updateInTextClusterOrder(inText: ClusterId[]);`. Otherwise, I proposed the signature above `updateClusterOrder(clusters: [ClusterId | [ClusterId, NoteNumber]])` specifically for the reason that clusters in a documents do end up both in notes and outside of them.

**Comment by cormacrelf** [comment]
>> It’s very costly to JSON-cycle every cluster in the document on every change, especially if most of them are untouched.

I'm just explaining the original divergence from an API like processCitationCluster, which requires passing every cluster when you insert one and need to bump all the note numbers, and also, it should be noted, can absolutely have inconsistent note numbers and AFAIK simply trusts citationsPre/Post for ordering-dependent things. If Zotero/Word can't operate any other way at the moment, then you simply don't benefit from this optimal API.

> I'm not entirely sure what JSON-cycling means here?

<details><summary>JSON-cycling</summary>

This is relevant to #20 as well. [This line](https://github.com/cormacrelf/citeproc-rs/blob/796ea0382392ae1befdc39f21162ed83b640ac29/crates/wasm/src/utils.rs#L70) is pretty much the following, but the JSON.parse is Rust code using `serde_json`:

```js
let array = [ { whatever: 1, other: "string" }, ... ];
// does needless stringifying and parsing and also allocates a Rust String during parse
array.map(x => JSON.parse(JSON.stringify(x)));
```

`serde-wasm-bindgen` would generate Rust code that's more akin to:

```js
// js
wasm.imports.jsObjectGetKey = (obj, key) => obj[key];
```
```rust
struct Whatever { whatever: u32, other: String };
impl Deserialize<...> for Whatever {
    fn deserialize(input: JsObject) -> Result<Self, Self::Error> {
        Whatever {
            whatever: jsObjectGetKey(input, js_string!("whatever")).as_u32()?,
            other: jsObjectGetKey(input, js_string!("other"))
                .as_string()?
                // allocates
                .to_owned(),
        }
    }
}
```

You can see how in #20, adding a string ID parameter to this object, adds an allocation either way. Multiplied by the number of items in the document. I haven't measured.

</details>

> Right, but my point is that just looking at what API methods are available as a naive client it is unclear what will happen for my example above

Yes, it isn't clear, and "just don't let it happen" is not enough. Here's why I have designed it the way it is now:

The 'truth' has to 'live' somewhere. The actual place it lives is in Word/GDocs fields. Anything other than blindly trusting the client on numbering means that some of the truth starts living in the driver, which is a mismatch that you will have to manage. If the processor was to doggedly avoid circumstances in which it couldn't decide on a sort order because of duplicated inText numbers, for example, then it would need to either (1) as you suggest, throw errors, (2) manage a list with insertion capability. Both are bad and I'll address them, but the main point is that the client code actually knows definitively what the order is, you simply need a way to tell the processor. You don't need the processor to do order-invariant-preserving list insertions and number-shifting -- you already have to do that. What I coded was the most efficient way to just tell the processor what the truth is, so it can do its thing. (Two truths: what the clusters contain, and what their numbers and relative ordering are. Both are pretty much optimal. You are right that the third truth, "what clusters are in the document" i.e. deletion, is suboptimal.)

<details><summary>Sidebar: what's wrong with insertCluster errors or maintaining consistency?</summary>

It's impossible to write an insertCluster that will not involve the driver's view of the document being inconsistent with the truth at some point. It only makes sense as part of a transaction that also includes operations to resolve that inconsistency.

* Say it doesn't accept a note/inText field. Then its ordering is either undefined or some default value like "the end" which could be incorrect. Errors can't help with that.
* Say it does. Think about operations like "Insert before position X" and "replace position X". You can't express these with a consistency-checking insertCluster without doing the numbering shifts BEFORE you run the operation. `[1,2,3,4] => [1,3,4,5] => [1,2,3,4,5]`. Disgusting. But also, `[1,3,4,5]` is an inconsistent state if those are note numbers.

What about (2) an insertCluster that manages numbering automatically? This is way worse.

This implies two things: (a) the citeproc-wasm API necessarily blows up to include a dozen different list manipulation operations such that no possible use case can cause invalid numberings, which is especially annoying because lists based on a { key: index } dictionary are the absolute worst to code because they cannot be iterated over easily, also likely buggy (I have tried it already, it was the worst); and (b) you will have to precisely orchestrate document manipulation in a way that we have established Word's APIs do not allow, in a way that perfectly matches the driver's internal manipulation. What's more, because note numbers create a multi-level list structure, it's still impossible not to have an inconsistent state.

</details>

**Upshot**: with this in mind, if it were to throw an error at any point, renumberClusters would be the correct place, because the snapshot of document truth you just attempted to provide is not consistent with itself. But I'm liking your original suggestion more. As an additional API, named `setDocumentFlow` or something like that. And also make the inText/note fields from cluster objects optional, documenting what client responsibilities are in either case. And it would validate the input such that note numbers are monotonically increasing. `setDocumentFlow([1, 2, { id: 3, note: 2 }, { id: 4, note: 2}, { id: 5, note: 1} ])` would fail at `{ id: 5, note: 1}` as note 2 has already been seen.

Is it more complicated with the new author-in-text stuff? That's probably for another issue, which we should ge to. At the very least I think your idea is flexible enough to accommodate that.

**Comment by adomasven** [comment]
> Is it more complicated with the new author-in-text stuff?

I don't think so. The author-in-text feature is still represented as citation clusters.

> Upshot: with this in mind, if it were to throw an error at any point, renumberClusters would be the correct place, because the snapshot of document truth you just attempted to provide is not consistent with itself. But I'm liking your original suggestion more

Great. Can you give an estimate for when this could be added? A matter of days or weeks?

**Comment by cormacrelf** [comment]
Give me a day or so, it isn’t too hard.
