### ISSUE TITLE
Wasm driver throws string errors

### ISSUE THREAD

**Issue by adomasven** [cormacrelf/citeproc-rs#25]
Wasm driver throws string errors from rust level code (instead of `Error` object). E.g. 

```could not parse cluster from host: data did not match any variant of untagged enum Cluster2```

String errors do not contain a stack trace, which makes them hard to debug.

**Comment by cormacrelf** [comment]
There was a reason I didn’t create Error objects, but I don’t recall why now. I think it was something to do with wasm-bindgen, but I don’t see any barrier today. Although at the end of the day, you will never get any deeper trace into Rust than the single stack frame showing a Driver function, see why below. You would get your own code, which would be helpful.

(Rust errors can be any type. In general, they do not include backtraces as that wouldn’t be “zero-cost” as Rust likes to put it. Storing a backtrace is an explicit operation. None of the errors in citeproc-rs do it. Although panicking creates a backtrace. If they happen, there is usually a problem with the library, but you’ll get a backtrace printed out for debug builds. There are a few panics (unwrap, expect, unreachable, unimplemented, panic) in the codebase still. General rule is that unwrap means “Cormac didn’t bubble up this client usage error and he should do that”, but the others are more likely logic errors.

FWIW the error you refer to is from generated code to deserialise Cluster2 from JSON. The deserialjzer gets a bit fragile with untagged enums (here detecting note vs inText and choosing an enum variant based on that) because unrecognised fields have to be treated as possibly matching a different variant. But that will be improved if we get rid of those fields and make it a struct instead, and you’ll get good errors like “unrecognised field” instead.

**Comment by adomasven** [comment]
> Although at the end of the day, you will never get any deeper trace into Rust than the single stack frame showing a Driver function

That's fine. At least you get an idea which calling code resulted in the error and what's the potential problem.

As for the reason for this error, it went away once I added an inText property. I assume you didn't make them optional in #24 yet?

**Comment by cormacrelf** [comment]
Correct.
